# Copyright 2020-2024 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Buf Action"
author: "Buf"
description: |-
  This action automates buf within GitHub Actions.
  It handles buf installation, caching, login to the registry, and running of buf commands based on GitHub event triggers.
  By default, the action will check lint, format, and breaking changes on pull requests.
  On pushes, it syncs the repository with the Buf Schema Registry, and on deletes, it archives the corresponding label.
  The action can be configured to skip steps, run only specific steps, or run steps on different events.

branding:
  icon: play
  color: blue

inputs:
  version:
    description: |-
      Version of the Buf CLI to use.
      Example:
        with:
          version: 1.32.2
    required: false
  username:
    description: |-
      Username for logging into the Buf Schema Registry.
    required: false
  token:
    description: |-
      API token for logging into the Buf Schema Registry.
    required: false
  domain:
    description: |-
      Domain for logging into the Buf Schema Registry.
    required: false
    default: "buf.build"
  github_actor:
    description: |-
      GitHub actor for API requests.
    required: false
    default: ${{ github.actor }}
  github_token:
    description: |-
      GitHub token for API requests.
    required: false
    default: ${{ github.token }}
  setup_only:
    description: |-
      Setup only the buf environment, optionally logging into the BSR, but without executing other commands.
    required: false
    default: "false"
  comment:
    description: |-
      Comment on the pull request with the results of the lint, format, and breaking steps.
    required: false
    default: ${{ github.event_name == 'pull_request' }}

  input:
    description: |-
      Input for the buf command.
    required: false
  config:
    description: |-
      Path to buf.yaml or data to use for configuration.
    required: false
  disable_symlinks:
    description: |-
      Disables following symlinks when reading sources or configuration from the local filesystem.
      By default, symlinks are followed by buf, but never followed on the Buf Schema Registry.
    required: false
    default: "false"
  paths:
    description: |-
      Limit to specific files or directories (separated by newlines).
      Example:
        with:
          paths: |
            proto/a/a.proto
            proto/a
    required: false
  exclude_paths:
    description: |-
      Exclude specific files or directories (separated by newlines).
      Example:
        with:
          exclude_paths: |
            proto/a/a.proto
            proto/a
    required: false
  exclude_imports:
    description: |-
      Excludes imports.
    required: false
    default: "false"

  lint:
    description: |-
      Whether to run the linting step.
      Runs by default on pull requests if the "buf skip lint" label is not applied.
    required: false
    default: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip lint') }}

  format:
    description: |-
      Whether to run the formatting step.
      Runs by default on pull requests if the "buf skip format" label is not applied.
    required: false
    default: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip format') }}

  breaking:
    description: |-
      Whether to run breaking change detection.
      Runs by default on pull requests if the "buf skip breaking" label is not applied.
    required: false
    default: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip breaking') }}
  breaking_against:
    description: |-
      Input to compare against for breaking change detection.
      Defaults to the base branch of the pull request or the commit before the push.
    required: false
    # TODO: change to #commit when available (its an alias for #tag).
    default: ${{ github.event.repository.clone_url }}#format=git,tag=${{ github.event.pull_request.base.sha || github.event.before }}
  breaking_against_config:
    description: |-
      Path to buf.yaml or data to use for the against configuration.
    required: false
  breaking_limit_to_input_files:
    description: |-
      Only run breaking checks against the files in the input.
      When set, the "breaking_against" input contains only the files in the input.
      Overrides path.
    required: false
    default: "false"

  push:
    description: |-
      Whether to run the push step. Runs by default on pushes.
      Sets "--git-metadata" with additional labels from the "labels" input.
    required: false
    default: ${{ github.event_name == 'push' }}
  push_create:
    description: |-
      Create the repository if it does not exist. Must set "push_create_visibility".
    required: false
    default: "true"
  push_create_visibility:
    description: |-
      Repository's visibility setting if created. Must be set if "push_create" is true.
      Must be either "public" or "private".
    required: false
  push_labels:
    description: |-
      Associates the labels with the pushed modules (separated by newlines).
      Labels are added in addition to the default labels from "--git-metadata".
      Example:
        with:
          push_labels: |
            label1
            label2
    required: false
  push_git_metadata:
    description: |-
      Set additional git metadata for the push using "--git-metadata".
    required: false
    default: "true"
  push_source_control_url:
    description: |-
      Set the source control URL for the pushed modules.
      To override the default, disable "push_git_metadata".
    required: false

  archive:
    description: |-
      Whether to run the archive step. Runs by default on deletes.
      Additional labels from the "labels" input are archived.
    required: false
    default: ${{ github.event_name == 'delete' }}
  archive_labels:
    description: |-
      Labels to archive (separated by newlines).
      Example:
        with:
          archive_labels: |
            label1
            label2
    required: false
    # See https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28#deleteevent
    default: |
      ${{ github.event.ref }}

runs:
  using: "node20"
  main: "./dist/index.js"
