# This workflow shows syncing changes only when the buf.yaml, README.md, LICENSE 
# or .proto files are modified.
# Caution: Restricting push can cause unintended behavior. Review the paths carefully.
name: Buf CI
on:
  push:
    paths:
      # Caution: This workflow could miss changes if the paths are not correctly specified.
      - '**.proto'
      - '**/buf.yaml'
      - '**/buf.lock'
      - '**/buf.md'
      - '**/README.md'
      - '**/LICENSE'
permissions:
  contents: read
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
