# This workflow downloads the latest version of buf as none is specified.
name: Buf CI
on:
  push:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf version
