# This workflow shows the default configuration for GitHub Enterprise Server.
name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          # Specify the public GitHub token to authenticate requests to github.com.
          # This is required when running on a private GitHub Enterprise instance.
          # Will be used when resolving buf versions and downloading buf binaries.
          public_github_token: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
