# This workflow runs checks on push events before pushing the changes to the BSR.
name: Buf CI
on:
  push:
  delete:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          # The token paramater is required to authenticate with the Buf Schema Registry.
          token: ${{ secrets.BUF_TOKEN }}
          lint: ${{ github.event_name == 'push' }}
          format: ${{ github.event_name == 'push' }}
          breaking: ${{ github.event_name == 'push' }}
