# This workflow syncs the changes to the BSR without running any checks.
name: ci
on:
  push:
  delete:
permissions:
  contents: read
jobs:
  buf:      
    name: Buf CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.1.0
        with:
          username: ${{ secrets.BUF_USERNAME }}
          token: ${{ secrets.BUF_TOKEN }}
