# This workflow downloads the version of buf specified in the .bufversion file.
name: ci
on:
  push:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "1.32.0" > .bufversion
      - uses: bufbuild/buf-action@v0.1.0
        with:
          setup_only: true
      - run: buf version
