# This workflow downloads the version of buf specified in the action input.
name: Buf CI
on:
  push:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.2
        with:
          setup_only: true
          version: 1.35.0
      - run: buf version
