# This workflow skips checks when `buf skip` is applied to a PR.
name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
jobs:
  buf:      
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.2
        with:
          username: ${{ secrets.BUF_USERNAME }}
          token: ${{ secrets.BUF_TOKEN }}
          lint: |
            github.event_name == 'pull_request' && \
            !contains(github.event.pull_request.labels.*.name, 'buf skip lint')
          format: |
            github.event_name == 'pull_request' && \
            !contains(github.event.pull_request.labels.*.name, 'buf skip format')
          breaking: |
            github.event_name == 'pull_request' && \
            !contains(github.event.pull_request.labels.*.name, 'buf skip breaking')
