name: Dependabot Update
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: write
  pull-requests: read
jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: rebuild
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          make build
          git add -A
          git commit -m "Build"
          git push -u origin HEAD:${{ github.event.pull_request.head.ref }}
